# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# Install tools required to convert markdown to PDF
- script: |
    sudo apt-get install pandoc texlive
    npm install -g pandoc-plantuml
  displayName: 'install required tools'


- script: |
    pandoc -F pandoc-plantuml -o README.pdf README.md
    ls -al
  displayName: 'pandoc convert'

- script: |
    wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.8/swagger-codegen-cli-2.4.8.jar -O swagger-codegen-cli.jar
    mkdir generated/
    mkdir generated/spring/
    mkdir generated/dart/
    java -jar swagger-codegen-cli.jar generate \
      -i api/swagger.json \
      -l spring \
      -o generated/java/
    java -jar swagger-codegen-cli.jar generate \
      -i api/swagger.json \
      -l dart \
      -o generated/dart/
    cd generated/java
    tar -czf spring.tar.gz *
    cd ..
    cd dart
    tar -czf dart.tar.gz *
    cd ../..
  displayName: 'Swagger Codegen'

- script: |
    echo '##vso[task.setvariable variable=releasetag]release'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'Set Release Tag if master branch'

- script: |
    echo '##vso[task.setvariable variable=releasetag]development'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/development')
  displayName: 'Set Release Tag if development branch'

- task: GithubRelease@0 
  condition: or(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')), and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development')))
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: benjaminSchilling33
    repositoryName: openrqm/openrqm-docs
    action: edit
    tagSource: manual
    tag: $(releasetag) 
    assetUploadMode: replace
    assets: |
        $(Build.Repository.LocalPath)/README.pdf
        $(Build.Repository.LocalPath)/generated/spring/spring.tar.gz
        $(Build.Repository.LocalPath)/generated/dart/dart.tar.gz